- name: fetch package
  get_url:
    url: "http://s3.amazonaws.com/influxdb/influxdb_{{ influxdb.version }}_amd64.deb"
    dest: "/usr/local/src/influxdb_{{ influxdb.version }}_amd64.deb"

- name: install package
  command: dpkg --skip-same-version -i /usr/local/src/influxdb_{{ influxdb.version }}_amd64.deb
  register: dpkg_result
  changed_when: "dpkg_result.stdout.startswith('Selecting')"

- name: set hostname to the ip4v
  lineinfile:
    dest: /opt/influxdb/shared/config.toml
    regexp: "hostname ="
    line: "hostname = \"{{ ansible_default_ipv4.address }}\""
    state: present
  notify:
    - restart influxdb