---
- service:
    name: influxdb
    state: started

- influxdb_users:
    host: 127.0.0.1:8086
    admin_username: root
    admin_password: root
    cluster_admins:
      - { name: root, password: root }
      - { name: max, password: mustermann }

- influxdb_databases:
    host: 127.0.0.1:8086
    admin_username: root
    admin_password: root
    databases:
      - example_a
      - example_b
