---
- service:
    name: influxdb
    state: started

- name: manage influxdb cluster admins
  influxdb_user:
    host: 127.0.0.1:8086
    api_username: root
    api_password: root
    username: "{{ item.name }}"
    password: "{{ item.password }}"
    state: "{{ item.state }}"
  with_items:
    - { name: root, password: root, state: present }
    - { name: maxi, password: mustermann, state: present }
    - { name: maxi, password: mustermann, state: absent }

- influxdb_database:
    host: 127.0.0.1:8086
    api_username: root
    api_password: root
    database: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { name: example, state: present }

- name: manage influxdb database users
  influxdb_user:
    host: 127.0.0.1:8086
    api_username: root
    api_password: root
    username: "{{ item.name }}"
    password: "{{ item.password }}"
    database: example
    database_admin: yes
    state: "{{ item.state }}"
  with_items:
    - { name: max, password: mustermann, state: present }
    - { name: max, password: mustermann, state: absent }

- influxdb_database:
    host: 127.0.0.1:8086
    api_username: root
    api_password: root
    database: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { name: example, state: absent }