---
- service:
    name: influxdb
    state: started

- influxdb_user:
    host: 127.0.0.1:8086
    api_username: root
    api_password: root
    username: "{{ item.name }}"
    password: "{{ item.password }}"
    state: "{{ item.state }}"
  with_items:
    - { name: root, password: root, state: present }
    - { name: max, password: mustermann, state: present }
    - { name: max, password: mustermann, state: absent }

- influxdb_database:
    host: 127.0.0.1:8086
    api_username: root
    api_password: root
    database: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { name: example_a, state: present }
    - { name: example_a, state: absent }
